
import { Inter } from 'next/font/google';
import Link from 'next/link';
import ScrollToTop from './ScrollToTop';
import './globals.css';
// import ScrollToTop from "react-scroll-to-top";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


import Layoutnavi from './Layoutnavi';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

   
 
  

  let name = 'sangbin'
  let style = "color:'green'"
  // let link = 'https://sodi9.store'
  let link = 'https://google.com'

  return (
    <html lang="en">
      <body className={inter.className}>

        <ScrollToTop />

        <ToastContainer
          position="bottom-center"
          autoClose={2000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />

        {/* <header></header> */}
        <Layoutnavi/>
  
        {children}
        

        {/* <footer></footer> */}
        <p className="title-sub">by dev {name}</p>
        <p>
          <a href={link}>port1.sodi9.store</a>
          {/* <a href="https://sodi9.store">port1.sodi9.store</a> */}
        </p>


        </body>
    </html>
  )
}
